project:
  type: book
  output-dir: main_notebook

book:
  title: "REU Research Report"
  author: "Olivia Davis and Gaoussou Toure" # Change to your names
  date: today
  date-format: iso
  downloads: [pdf]
  sidebar: 
    collapse-level: 1
    search: false
  # Update the chapters when new qmd files are added.
  chapters:
    - index.qmd
    - 01-week_0611_0617.qmd
    - references.qmd

bibliography: references.bib # Use bibtex editing tool such as BibDesk
csl: nature.csl

# You don't need to worry about the following configs about formatting. 
# However, feel free to modify them if you like.
format:
  html:
    light: [default]
    fontsize: "18px"
    toc-title: Contents
    toc-depth: 5
    code-copy: true
    code-fold: true
    code-tools: true
    highlight-style: printing
    code-block-bg: true
    code-overflow: wrap
    linkcolor: "#5289c8"
  pdf:
    latex_engine: xelatex
    documentclass: book
    classoption: oneside
    geometry: "left=1in,right=1in,top=1in,bottom=1in"
    lof: false
    lot: false
    toc-title: Contents
    toc-depth: 5
    fig-cap-location: bottom
    tbl-cap-location: bottom
    colorlinks: true
    fontsize: 11pt
    keep-tex: false
    highlight-style: printing
    code-block-bg: "#f2f2f2"
    code-block-border-left: "#f2f2f2"
    code-overflow: wrap
    include-in-header: heading.tex

latex-auto-install: true


